# Site settings
title: Brian Dorsey's audioblog
email: brian@dorseys.org
description: >
  This is a spoken word audio blog. The topics are probably going to be
  fairly diverse. I'll try to include a summary early in each episode, so you
  can skip anything that doesn't sound interesting. ;) I'm a Developer
  Advocate for Google Cloud Platform, so there will certainly be cloud
  related technical content. I'm learning to record decent audio, so I'll
  likely be talking about that as well. I'll post occasional conversations
  with developers and startups about what they're building and how they're
  doing it. And whatever else comes to mind. I'd love to hear your thoughts,
  feedback and ideas for this audioblog. Please send them via <a
  href="https://twitter.com/briandorsey">Twitter</a>, <a
  href="https://plus.google.com/+BrianDorsey">Google Plus</a>, or <a
  href="mailto:brian@dorseys.org">email</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
mediaurl: "http://media.briandorsey.info"
url: "http://audioblog.briandorsey.info" # the base hostname & protocol for your site
twitter_username: briandorsey
github_username:

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown
