# Site settings
title: Your awesome title
email: brian@dorseys.org
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://audioblog.briandorsey.info" # the base hostname & protocol for your site
twitter_username: briandorsey
github_username:

# Build settings
markdown: kramdown
